### ISSUE TITLE
Compatibility with aurelia rc-1.0.0

### ISSUE THREAD

**Issue by Archelyst** [MarcScheib/aurelia-notification#4]
Could you please make this compatible with the recent version of aurelia (rc-1.0.0)? I'm getting

```
lifecycle.js:10 Uncaught (in promise) TypeError: Cannot read property 'canActivate' of undefined
    at invokeLifecycle (http://dev-local:8835/jspm_packages/github/MarcScheib/aurelia-notify@0.5.0/lifecycle.js:10:24)
    at http://dev-local:8835/jspm_packages/github/MarcScheib/aurelia-notify@0.5.0/notification-service.js:60:47
```

and

```
Uncaught (in promise) Error: BindingLanguage must implement inspectTextContent().
    at mi (http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:734:11)
    at BindingLanguage.inspectTextContent (http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:751:7)
    at ViewCompiler._compileNode (http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:2532:79)
    at ViewCompiler._compileNode (http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:2552:33)
    at ViewCompiler.compile (http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:2499:12)
    at http://dev-local:8835/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:3146:50
```

**Comment by MarcScheib** [comment]
Hi @Tim-Erwin,
can you set up a reproduction of this? I am using 0.5.0 already with rc-1.0.0 and it is working without problems in my application.
Did you specify another view model which is not existing? It seems like the VM is not available.

**Comment by MarcScheib** [comment]
I am closing this as there is no reproduction of the mentioned error.
